# Generated by Django 4.0.4 on 2022-07-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_user_school_alter_profile_user_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_class',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_class_letter',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_class_number',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
