# Generated by Django 4.0.4 on 2022-07-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_user_class_profile_user_class_letter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='service/default.jpg', upload_to='users_photos', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_class_letter',
            field=models.CharField(blank=True, max_length=1, verbose_name='Буква класса'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_class_number',
            field=models.CharField(blank=True, max_length=2, verbose_name='Номер класса'),
        ),
    ]
