# Generated by Django 4.0.4 on 2022-07-19 10:40

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, validators=[mainapp.models.validate_mat]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, validators=[mainapp.models.validate_mat]),
        ),
    ]
